### ISSUE TITLE
如何与react组件结合？

### ISSUE THREAD

**Issue by codering** [Lucifier129/relite#1]
我当前的项目主要的时react + react-router。
现在用relite重构，我想到的最简单的方案就是在路由对应的组件上动手脚
```js

    componentDidMount() {
        this.unsubscribe = store.subscribe(() => this.forceUpdate()) 
    }
    
    componentWillUnmount() {
        this.unsubscribe && this.unsubscribe()
    }

```

当然也可以写个hoc统一处理， 但用forceUpdate感觉比较暴力。。。

还有其他比较好的方案吗？

**Comment by Lucifier129** [comment]
可以这样做，`forceUpdate` 在明确知道需要更新视图的场景下是合理的。

`relite` 只有在 state 发生变化的时候才会 pubilsh 一个订阅消息，而当 nextState !== currentState 时，view 需要更新，很合理。

**Comment by codering** [comment]
@Lucifier129  我写了个[demo](https://github.com/codering/relite-demo), 
看下那2个hoc函数封装有问题吗？ 如何改进？ 
谢谢！

**Comment by Lucifier129** [comment]
@codering 看起来还可以。但是怎么做服务端渲染呢？

**Comment by codering** [comment]
暂时不考虑服务端渲染。

**Comment by Lucifier129** [comment]
那挺好的，可以把 `createLogger` 也写进 hoc 里，配置 `loggerName` 

``` javascript
@container({
    initialState,
    actions,
    loggerName: 'XXX'
})
class XXX
```

**Comment by codering** [comment]
恩，`plugins`也需要在`componentWillUnmount` 时做清理。。。

**Comment by Lucifier129** [comment]
建议[这里](https://github.com/codering/relite-demo/blob/master/src/module/hoc/container.js) 把 store 放到 component.store 属性里，在 constructor 里实例化，避免多次使用该组件时造成冲突。

这样做的另一个好处时，willUnmount 时清理都不用了，反正全部引用都抛掉了（createStore 不会在闭包里保留任何数据。）

**Comment by codering** [comment]
是这样做吗？

``` js
          constructor(props, context) {
                super(props, context)
                this.store = createStore(actions, initialState)
                ...
                ...
            }

            getChildContext() {
                return { store: this.store }
            }

```

**Comment by Lucifier129** [comment]
是的。createStore 很轻量，不会造成性能问题，所以跟着 Component 的实例数量走是可行的。

**Comment by codering** [comment]
已改。 @Lucifier129 非常感谢！
